#!/usr/bin/env bash
# Reset between multi-UAV runs: stop the fleet, clear per-run runtime state.
#
# Only per-run runtime artifacts are removed. Source (src/, third_party/),
# generated worlds and scenario metadata are never touched.
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/multi_uav_common.sh"

mu_log "reset: stop fleet"
mu_kill_all
sleep 2

rm -rf "${MU_WS}/logs/multi_uav"            2>/dev/null || true
rm -rf "${MU_WS}/build/training_city/multi_uav" 2>/dev/null || true
rm -f  "${MU_WS}/logs/battery_done.marker"  2>/dev/null || true
# Scene receipt is regenerated by the scenario prepare step of the next run.
rm -f  "${MU_WS}/build/training_city/active_launch.json" 2>/dev/null || true

if mu_any_alive; then
    mu_log "WARN: processes survived reset:"
    pgrep -af "uav_navigation_nod[e]|multi_uav_mavros_sit[l]|gzserve[r]|px[4]" || true
    exit 1
fi
mu_log "reset done"
